spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    context-path: /api